### ISSUE TITLE
Less aggressive separator detection

### ISSUE THREAD

**Issue by alf-mindshift** [kostafey/ejc-sql#113]
I suggest the following change:

```
(defn get-separator-re [separator]
  "We only look for the separator as the first character of the line.
E.g. you can use default separator char `/` in this query:
      SELECT count / 1000 FROM urls WHERE path like '%http://localhost%'
      /
      SELECT 1"
  (re-pattern
   (format
    "(?m)^\\s*%s"
    ;; Escape chars for `$$` separators.
    (.replace separator "$" "\\$"))))
```

**Comment by kostafey** [comment]
The ending separator/delimiter case should be considered too since it's a common practice e.g. for MySQL:
http://www.mysqltutorial.org/mysql-stored-procedure/mysql-delimiter/

**Comment by kostafey** [comment]
Ok, looks like I should explain `ejc-sql` separators usage a little bit. `ejc-sql` attempts to be 2 things simultaneously: easy ad-hoc client for databases like h2 or SQLite and full-fledged client for databases like Oracle. There are 2 meanings of separators in `ejc-sql`.

* First is a border to determine the area in Emacs buffer should be passed to evaluation. e.g.:
```sql
SELECT * FROM one_table
/
SELECT * FROM other_table
```
So, you don't need to select SQL snippet, simply put point (cursor) into code snippet and press <kbd>C-c C-c</kbd> (or desired keybinding). Borders of SQL will be found by Emacs buffer begin/end or this `/` separator. 

* Second meaning is actually delimiter of SQL statements inside SQL snippet passed to evaluation. They are evaluated sequentially (one by one) as separate SQL statements (independent transactions).

E.g. you can easily fill you h2 database:
```sql
INSERT INTO product (name, price) VALUES ('socks', 1.25);
INSERT INTO product (name, price) VALUES ('sweater', 14.56);
INSERT INTO product (name, price) VALUES ('jeans', 25.30);
/
SELECT * FROM other_table
```
Here, the first part is a single snippet passed to `ejc-sql` but evaluated by 3 independent SQL statements. Furthermore, you can change the delimiter inside this snippet, e.g. for MySQL:
```sql
DELIMITER $$
CREATE PROCEDURE GetAllProducts()
BEGIN
  SELECT *  FROM products;
END $$
/
CALL GetAllProducts();
```
Anyway, we can't use `;` for Oracle to separate SQL statements since it's a part of its procedures syntax:
```sql
CREATE OR REPLACE PROCEDURE welcome_msg (p_name IN VARCHAR2) 
IS
BEGIN
dbms_output.put_line ('Welcome '|| p_name);
END;
/
EXEC welcome_msg ('John Doe')
```
That's why `:separator "/"` is used for Oracle db connections configuration, to seperate SQL statements only by this `/` symbol (https://github.com/kostafey/ejc-sql#oracle-connection).

Probably, this behavior should be reconsidered. @alf-mindshift, what do you think?
Anyway, the last commit should fix the problem with division in SQL for connections, configured with `:separator` parameter:
```sql
SELECT 10/2 math FROM dual
```

**Comment by alf** [comment]
Being able to do math solves my issue perfectly. Thank you for the quick turn around time.

While I do find the separator-stuff a bit confusing, my feeling is that this issue was more a bug than a user error.
