### ISSUE TITLE
Misaligned candidates in auto-complete-popup with emacs native line numbers

### ISSUE THREAD

**Issue by pepperblue** [kostafey/ejc-sql#120]
When emacs native line numbers are enabled, auto-complete-candidates in popup are misaligned:
![misaligned](https://user-images.githubusercontent.com/3543271/73647790-8df8c000-467c-11ea-8cd7-6e1bc6f23215.jpg)
Using `linum-mode` alignment is ok ...
![wellaligned](https://user-images.githubusercontent.com/3543271/73647823-9b15af00-467c-11ea-9e25-fe522af28763.jpg)

**Comment by kostafey** [comment]
This problem is not related to `ejc-sql` itself, it's an Emacs `auto-complete` issue, actually even deeper - `popup-el`. Unfortunately, `popup-el` is not under active development at this moment. You can try this fork https://github.com/kostafey/popup-el.
Furthermore, probably we should consider migrating to `company-mode` for code completion.

**Comment by pepperblue** [comment]
Thank you for the information. Your fork of `popup-el` doesn't help in this case ...

**Comment by kostafey** [comment]
Actually, this issue duplicates https://github.com/kostafey/ejc-sql/issues/67
