### ISSUE TITLE
multiple statements error

### ISSUE THREAD

**Issue by vanniuner** [kostafey/ejc-sql#129]
I just use the multiple statements. An error appears , and it showes that "Error: ORA-00911: invalid character."
But if I execute a single statement which does not contain ';' . Nothing wrong appears. 
Is  this a bug? How to fix it ?

**Comment by kostafey** [comment]
@vanniuner, what is your database type? Could you also provide an example query you are trying to execute?

**Comment by vanniuner** [comment]
update JS_YF set F_DD='3063795' WHERE F_PKEY='2020030300003';
update JS_YF set F_SD='jxssswN' WHERE F_PKEY='2020031800001';
/

**Comment by kostafey** [comment]
First of all, please update with the lastest commit.
Since you use `:separator "/"` in your database connection configuration you can't use `;` as transaction delimiter, because you expect it as a part of SQL syntax. E.g. for Oracle databases symbol `;` used in stored procedures code definitions. If you want to pass many statements (they will be executed as separate transactions) and obtain a list of results, you should provide a delimiter explicitly. E.g.

```sql
delimiter $$
update JS_YF set F_DD='3063795' where F_PKEY='2020030300003'$$
update JS_YF set F_SD='jxss' where F_PKEY='2020031800001'$$
/
select * from update JS_YF
```
or even like this:
```sql
delimiter ;
update JS_YF set F_DD='3063795' where F_PKEY='2020030300003';
update JS_YF set F_SD='jxss' where F_PKEY='2020031800001';
```

**Comment by vanniuner** [comment]
I try to execute multi statements, but it still reports an error even I use the delimiter ;

**Comment by kostafey** [comment]
The actual version at this moment is `ejc-sql 20200325.1455` (https://melpa.org/#/ejc-sql), so please update it. Furthermore, please note, GNU Emacs 26.3 (or latest version) is required.

**Comment by vanniuner** [comment]
I appreciate your reply. I try it ,and it succeeds.
