### ISSUE TITLE
Symbol’s function definition is void: :done

### ISSUE THREAD

**Issue by rrudakov** [kostafey/ejc-sql#93]
After executing every query I see the error in echo area:
```
Symbol’s function definition is void: :done
  in wrapped Clojure->Elisp function: ejc_sql.connect$complete_query@18edd25f
  elisp: (ejc-complete-query "/tmp/ejc-sql-result-5.txt" :start-time '(23761 17347 588700 37000 ) :status :done :display-result t :mode 'ejc-result-mode :connection-name nil :db nil)
```

The issue can be solved by deleting ~/.emacs.d/elpa/ and reinstall all packages.

I've tried to clean /tmp dir, it doesn't help.

Emacs version: GNU Emacs 26.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.8) of 2019-04-12

Package version: latest from MELPA.

**Comment by kostafey** [comment]
The only place `:done` is used in Elisp https://github.com/kostafey/ejc-sql/blob/master/ejc-sql.el#L494
I guess the problem was because of more than one different versions of the package(s) located in `~/.emacs.d/elpa/`. Sometimes it happens because of errors during the packages update process (if older ones did not deleted).
Could you confirm that the issue is not reproducible anymore?

**Comment by rrudakov** [comment]
I've removed `~/.emacs.d/elpa/ejc-sql-20190511.1347` directory, then reinstall package from MELPA. Buy it still reprodusable.

**Comment by kostafey** [comment]
@rrudakov could you please provide the full stack trace by run `M-x toggle-debug-on-error [RET]` first.

**Comment by rrudakov** [comment]
After updating to the latest version, seems like it's not reproducible anymore. Thank you.
