### ISSUE TITLE
Leverage orgtbl-mode in ejc-results-mode

### ISSUE THREAD

**Issue by alf** [kostafey/ejc-sql#97]
By making a slight modification to the table formatting syntax used in `ejc-sql`, we can enable `orgtbl-mode` and gain a huge number of sophisticated functionality for post processing and browsing our query results.

The required change consist of prepending and appending a `|` to each line of the table.

Note that this change also aligns our format to the format used by the [print-table](https://github.com/clojure/clojure/blob/93d13d0c0671130b329863570080c72799563ac7/src/clj/clojure/pprint/print_table.clj#L11) function in `clojure.pprint`.

If you agree to this change then we also need to make the results buffer editable and keep undo state.

**Comment by stardiviner** [comment]
This sounds interesting :)

**Comment by kostafey** [comment]
Related comment: https://github.com/kostafey/ejc-sql/issues/95#issuecomment-495764463

The main advantage of the current implementation is simplicity.
You can fetch big amounts of data with trivial syntax highlight (`ejc-result-mode`). Big result sets can be fetched from query to query many times without huge memory consumption since there is no undo history.

There is another good table implementation for Emacs: `emacs-ctable` (https://github.com/kiwanami/emacs-ctable). It uses model and view layers. With this approach (by tiny modifications of `emacs-ctable`), we can e.g. show only part of the long field (for `varchar(256)` or `clob`) and show the full text of the field by request. It's very useful for result sets with a big amount of long fields. Furthermore, it doesn't require any formation to the table from the backend at all. 

On the other hand, current results are simple files with text formatted as tables, so we can use tools like `find`, `grep` and so on.

So, all approaches have their own pros and cons so, the best solution is to provide a choice for the user.

Yes, `orgtbl-mode` can be used by default.

**Comment by stardiviner** [comment]
Emm, I agree. Sounds reasonable.

**Comment by alf** [comment]
Just a follow up question regarding backwards compatibility. Does that include the table format or can I always include leading and trailing pipes?

**Comment by kostafey** [comment]
The other reason to keep `ejc-result-mode` as major-mode independently of minor-mode.

I use `Meta-<arrow>` keys to navigate amoung windows:
```lisp
(windmove-default-keybindings 'meta)           ; M-up/down/left/right
```
It's especially useful with this function:
```lisp
(defun eframe-windmove-do-window-select (orig-fun &rest args)
  (let ((other-window (apply 'windmove-find-other-window args)))
    (if (and (null other-window)
             (> (length (frame-list)) 1))
        (let ((direction (car args))
              (f (selected-frame)))
          (if (member direction '(right left))
              (while (eq f (selected-frame))
                (cond ((equal direction 'right) (next-multiframe-window))
                      ((equal direction 'left) (previous-multiframe-window))))))
      (apply orig-fun args))))

(advice-add 'windmove-do-window-select
            :around #'eframe-windmove-do-window-select)
```
So, if you have many monitors, you can open `*ejc-sql-output*` buffer in the second Emacs frame on different monitor and jump by `M-right` & `M-left` amoung SQL edit buffer and result set table.

`orgtbl-mode-map` breaks this possibility. We shouldn't touch it, since it's expected behavior for `orgtbl-mode` users. But if the major-mode remains as `ejc-result-mode`, they still can create hooks like that:
```lisp
(define-key orgtbl-mode-map (kbd "M-<left>") nil)
(define-key orgtbl-mode-map (kbd "M-<right>") nil)
(define-key orgtbl-mode-map (kbd "M-<down>") nil)
(define-key orgtbl-mode-map (kbd "M-<up>") nil)
(define-key orgtbl-mode-map (kbd "C-M-<left>") 'org-table-move-column-left)
(define-key orgtbl-mode-map (kbd "C-M-<right>") 'org-table-move-column-right)
(define-key orgtbl-mode-map (kbd "C-M-<up>") 'org-table-move-row-up)
(define-key orgtbl-mode-map (kbd "C-M-<down>") 'org-table-move-row-down)
```

**Comment by stardiviner** [comment]
Even though I don't have second monitor, but this configuration looks interesting. I will record it down. :)

**Comment by kostafey** [comment]
Implemented.
